// AUTO-GENERATED by scripts/generate-tag-options.mjs — do not edit by hand.
// Regenerated before dev/build from the tags in src/content/tags.
export type TagOption = { value: string; label: string };
export const tagOptions: { sectors: TagOption[]; services: TagOption[] } = {
  "sectors": [
    {
      "value": "retail",
      "label": "Retail"
    },
    {
      "value": "office",
      "label": "Office/Warehouse"
    },
    {
      "value": "healthcare",
      "label": "Healthcare"
    },
    {
      "value": "government",
      "label": "Government"
    },
    {
      "value": "institutional",
      "label": "Institutional"
    },
    {
      "value": "residential",
      "label": "Residential"
    },
    {
      "value": "self-storage",
      "label": "Self-Storage"
    },
    {
      "value": "mixed-use",
      "label": "Mixed Use"
    },
    {
      "value": "federal-government",
      "label": "Federal Government"
    },
    {
      "value": "grocery",
      "label": "Grocery"
    }
  ],
  "services": [
    {
      "value": "construction-coordination-supervision",
      "label": "Construction Coordination, Supervision, and Documentation"
    },
    {
      "value": "geotechnical-investigations",
      "label": "Geotechnical Investigations"
    },
    {
      "value": "initial-program-development",
      "label": "Initial Program Development"
    },
    {
      "value": "project-planning-coordination",
      "label": "Project Planning & Coordination"
    },
    {
      "value": "rfp-development",
      "label": "RFP Development"
    },
    {
      "value": "site-analysis-feasibility",
      "label": "Site Analysis, Property Assessment & Feasibility Studies"
    },
    {
      "value": "contractor-bidding-selection",
      "label": "Contractor Bidding / Clarification / Selection"
    },
    {
      "value": "environmental-assessments",
      "label": "Environmental Assessments"
    },
    {
      "value": "pre-construction-services",
      "label": "Pre-Construction Services"
    },
    {
      "value": "project-contractor-procurement",
      "label": "Project Contractor Procurement"
    },
    {
      "value": "requests-for-information",
      "label": "Requests for Information / Design Issue Recommendation / Resolution"
    },
    {
      "value": "schematic-design-development",
      "label": "Schematic Design and Design Development Documents"
    },
    {
      "value": "construction-management-services",
      "label": "Construction Management Services"
    },
    {
      "value": "contractor-negotiations-contracts",
      "label": "Contractor Negotiations / Contract Development"
    },
    {
      "value": "government-agency-coordination",
      "label": "Government Agency Coordination"
    },
    {
      "value": "hazardous-material-surveys",
      "label": "Hazardous Material Surveys"
    },
    {
      "value": "special-construction-design-coordination",
      "label": "Special Construction Design Coordination"
    },
    {
      "value": "owners-representation",
      "label": "Owner's Representation / Project Management Oversight"
    },
    {
      "value": "project-schedule",
      "label": "Project Schedule"
    },
    {
      "value": "title-survey-reviews",
      "label": "Title & Survey Reviews"
    },
    {
      "value": "utility-coordination",
      "label": "Utility Coordination"
    },
    {
      "value": "drone-technologies",
      "label": "Drone Technologies"
    },
    {
      "value": "highway-access",
      "label": "Highway Access"
    },
    {
      "value": "proforma-analysis-budgeting",
      "label": "Proforma Analysis / Hard & Soft Cost Budgeting"
    },
    {
      "value": "testing-agency-coordination",
      "label": "Testing Agency Coordination"
    },
    {
      "value": "project-estimating-value-engineering",
      "label": "Detailed Project Estimating and Value Engineering"
    },
    {
      "value": "environmental-permitting-requirements",
      "label": "Environmental Permitting Requirements"
    },
    {
      "value": "tenant-delivery-coordination",
      "label": "Tenant Delivery / Construction Coordination"
    },
    {
      "value": "cash-flow-analysis",
      "label": "Cash Flow Analysis"
    },
    {
      "value": "land-development-requirements",
      "label": "Land Development Requirements"
    },
    {
      "value": "project-schedule-management",
      "label": "Project Schedule Management"
    },
    {
      "value": "contract-budget-management",
      "label": "Contract Management / Budget Management"
    },
    {
      "value": "existing-utility-identification",
      "label": "Existing Utility Identification and Assessments"
    },
    {
      "value": "land-development-zoning-approvals",
      "label": "Land Development & Zoning Approvals"
    },
    {
      "value": "bank-billing-inspection-coordination",
      "label": "Bank Billing & Inspection Coordination / Government Agency"
    },
    {
      "value": "highway-permitting",
      "label": "Highway Permitting"
    },
    {
      "value": "landlord-tenant-lease-requirements",
      "label": "Landlord and Tenant Lease Construction Requirements"
    },
    {
      "value": "escrow-letter-of-credit-reductions",
      "label": "Escrow & Letter of Credit Reductions"
    },
    {
      "value": "npdes-permitting",
      "label": "NPDES Permitting"
    },
    {
      "value": "opinions-of-probable-cost",
      "label": "Opinions of Probable Cost / Project Budgeting"
    },
    {
      "value": "environmental-permitting",
      "label": "Environmental: Stream Crossing / Sewer Modules"
    },
    {
      "value": "feasibility-project-schedule",
      "label": "Project Schedule"
    },
    {
      "value": "utility-service-coordination",
      "label": "Utility Service Coordination"
    },
    {
      "value": "building-construction-permits",
      "label": "Building / Construction Permits"
    },
    {
      "value": "pre-construction-meetings",
      "label": "Pre-Construction Meetings"
    },
    {
      "value": "demolition",
      "label": "Demolition"
    },
    {
      "value": "grant",
      "label": "Grant"
    },
    {
      "value": "landscaping",
      "label": "Landscaping"
    },
    {
      "value": "project-management",
      "label": "Project Management"
    },
    {
      "value": "remediation",
      "label": "Remediation"
    },
    {
      "value": "signage",
      "label": "Signage"
    }
  ]
};
